from ..base import MedicalDevice

class Ventilator(MedicalDevice):
    device_name = "Ventilator Digital Twin"
    device_class = "Class II"

    def get_default_subsystems(self):
        return [
            "PneumaticsControl", 
            "MainControlUnit", 
            "PowerSupply", 
            "GasMixer", 
            "SafetyMonitor", 
            "PatientInterface", 
            "Display&UI"
        ]

    def get_architecture(self):
        """
        Define high-level component categories per subsystem.
        Specific components are dynamically generated by RAG-driven generator.
        """
        return {
            "PneumaticsControl": [
                {"name": "Blower Turbine", "category": "Hardware (Mechanical)"},
                {"name": "Proportional Valve", "category": "Hardware (Mechanical)"},
                {"name": "Manifold Enclosure", "category": "Enclosure Packaging"},
                {"name": "Vibration Isolators", "category": "Enclosure Packaging"},
                {"name": "Motor Commutation", "category": "Embedded Software"}
            ],
            "MainControlUnit": [
                {"name": "ESP32-S3 MCU", "category": "Hardware (Electronic)"},
                {"name": "I2C Sensor Bus", "category": "Hardware (Electronic)"},
                {"name": "FreeRTOS Kernel", "category": "Embedded Software"},
                {"name": "Lung Control Loop", "category": "Application Software"},
                {"name": "Temporal Data Logger", "category": "Application Software"}
            ],
            "PowerSupply": [
                {"name": "Medical AC/DC", "category": "Hardware (Electronic)"},
                {"name": "ISO 60601 Isolation XFMR", "category": "Hardware (Electronic)"},
                {"name": "Li-ion Battery Pack", "category": "Hardware (Electronic)"},
                {"name": "Battery Management App", "category": "Application Software"}
            ],
            "GasMixer": [
                {"name": "O2 Galvanic Cell", "category": "Hardware (Electronic)"},
                {"name": "Solenoid Valve Array", "category": "Hardware (Mechanical)"},
                {"name": "High-Pressure O-Rings", "category": "Hardware (Mechanical)"},
                {"name": "Oxygen Mixing Logic", "category": "Embedded Software"}
            ],
            "SafetyMonitor": [
                {"name": "ATTiny Watchdog MCU", "category": "Hardware (Electronic)"},
                {"name": "Relief Valve (Pop-off)", "category": "Hardware (Mechanical)"},
                {"name": "Leakage Current Monitor", "category": "Hardware (Electronic)"},
                {"name": "ISO 14971 Trip Logic", "category": "Embedded Software"}
            ],
            "PatientInterface": [
                {"name": "Dual-Limb Circuit", "category": "Enclosure Packaging"},
                {"name": "HME Filter Housing", "category": "Enclosure Packaging"},
                {"name": "Proximal Flow Sensor", "category": "Hardware (Electronic)"},
                {"name": "Expiratory PEEP Valve", "category": "Hardware (Mechanical)"}
            ],
            "Display&UI": [
                {"name": "10-inch Touch Panel", "category": "Hardware (Electronic)"},
                {"name": "Bezel Housing", "category": "Enclosure Packaging"},
                {"name": "EMI Shielding Gasket", "category": "Enclosure Packaging"},
                {"name": "LVGL GUI Framework", "category": "Application Software"}
            ]
        }

    def get_detailed_components(self):
        """Component specifications for simulation integration."""
        return {
            "Blower Turbine": {"type": "Actuator", "model": "Micronel U65", "control": "PWM (25kHz)", "speed": "60k RPM"},
            "ESP32-S3 MCU": {"type": "MCU", "model": "ESP32-S3-WROOM", "bus": "SPI/I2C"},
            "Proximal Flow Sensor": {"type": "Sensor", "model": "Sensirion SFM3019", "interface": "I2C", "accuracy": "3%"},
            "Relief Valve (Pop-off)": {"type": "Mechanical Safety", "threshold": "80 cmH2O", "response": "<100ms"},
            "ISO 60601 Isolation XFMR": {"type": "Safety Isolation", "rating": "4kV RMS", "leakage": "< 100uA"},
            "Temporal Data Logger": {"type": "Software Module", "frequency": "100Hz", "storage": "NAND Flash"},
            "Leakage Current Monitor": {"type": "Safety Hardware", "standard": "IEC 60601-1", "trip_point": "300uA"}
        }

    def get_software_stack(self):
        return []

    def get_design_constraints(self):
        return {
            "flow_rate_range": (5, 120),
            "max_pressure": 60,
            "latency_ms": 10
        }

    def get_default_interfaces(self):
        return [
            {"source": "PowerSupply", "target": "MainControlUnit", "signal": "3.3V / 5V Rail"},
            {"source": "PowerSupply", "target": "PneumaticsControl", "signal": "24V High Current"},
            {"source": "MainControlUnit", "target": "PneumaticsControl", "signal": "Blower PWM Control"},
            {"source": "MainControlUnit", "target": "Display&UI", "signal": "SPI / RGB Display Data"},
            {"source": "PatientInterface", "target": "PneumaticsControl", "signal": "Flow Returns"},
            {"source": "PneumaticsControl", "target": "PatientInterface", "signal": "Pressurized Air"},
            {"source": "PatientInterface", "target": "MainControlUnit", "signal": "I2C Telemetry"},
            {"source": "SafetyMonitor", "target": "PneumaticsControl", "signal": "Hardware Kill-Switch"},
            {"source": "MainControlUnit", "target": "SafetyMonitor", "signal": "Heartbeat (UART)"},
            {"source": "GasMixer", "target": "PneumaticsControl", "signal": "O2 Blended Gas"}
        ]

    # ══════════════════════════════════════════════════════════════════════════
    # IEC 62304 §5.5: DETAILED DESIGN - Now Dynamically Generated
    # BOM, PCB, Firmware, and Verification Plan are generated by DynamicDesignGenerator
    # No hardcoded values - all driven by RAG queries and requirements
    # ══════════════════════════════════════════════════════════════════════════
